const appLinks=[['🧮','Calculator','01-calculator.html'],['✅','Tasks','02-tasks.html'],['⏱','Stopwatch','03-stopwatch.html'],['🌤','Weather','04-weather.html'],['🎵','Music','29-music.html'],['₿','Crypto','32-crypto.html']];
const settingsItems=['🖥 Display','🔊 Sound','🌐 Network','🔒 Privacy','⚡ Battery','🎨 Theme','🌙 Dark Mode'];
const apps=[
  {name:'Terminal',icon:'💻',color:'#00e0ff',content:()=>`<div style="font-family:JetBrains Mono,monospace;font-size:12px;color:#00ff41;background:#000;padding:12px;border-radius:8px;min-height:180px"><div style="color:#00e0ff;margin-bottom:6px">DEVOS Terminal v3.0</div><div id="term-out" style="max-height:160px;overflow-y:auto"></div><div style="display:flex;align-items:center;gap:6px;margin-top:8px;border-top:1px solid #0a2a0a;padding-top:8px"><span style="color:#00e0ff">$</span><input id="term-in" style="flex:1;background:transparent;border:none;color:#00ff41;font-family:JetBrains Mono,monospace;font-size:16px;outline:none" placeholder="type help..." autocomplete="off" onkeydown="terminalKey(event)"></div></div>`},
  {name:'Files',icon:'📁',color:'#818cf8',content:()=>`<div id="files-view"><div style="text-align:center;padding:20px;color:var(--muted)">Loading...</div></div>`,init:'initFiles'},
  {name:'Browser',icon:'🌐',color:'#34d399',content:()=>`<div><div style="display:flex;gap:6px;margin-bottom:10px"><button onclick="browserBack()" style="background:var(--card2);border:1px solid var(--border);color:var(--muted);width:30px;height:30px;border-radius:6px;cursor:pointer">←</button><div id="browser-url" style="flex:1;background:var(--bg);border:1px solid var(--border);border-radius:6px;padding:6px 10px;font-family:JetBrains Mono,monospace;font-size:11px;color:var(--accent)">https://devos.io</div><button onclick="browserGo()" style="background:linear-gradient(135deg,var(--accent),var(--accent2));border:none;color:#000;padding:6px 12px;border-radius:6px;cursor:pointer;font-size:11px;font-weight:700">Go</button></div><div id="browser-page" style="background:var(--card2);border-radius:10px;padding:20px;text-align:center"><div style="font-size:40px;margin-bottom:8px">🌐</div><p style="color:var(--muted);font-size:12px;margin-bottom:12px">DevOS Browser</p><div style="display:flex;gap:8px;justify-content:center;flex-wrap:wrap"><button onclick="loadSite('https://devos.io')" style="background:var(--card3);border:1px solid var(--border);color:var(--text);padding:7px 12px;border-radius:8px;cursor:pointer;font-size:11px">devos.io</button><button onclick="loadSite('https://github.com')" style="background:var(--card3);border:1px solid var(--border);color:var(--text);padding:7px 12px;border-radius:8px;cursor:pointer;font-size:11px">github.com</button></div></div></div>`},
  {name:'Music',icon:'🎵',color:'#f472b6',content:()=>`<div style="text-align:center;padding:8px"><div id="os-disc" style="font-size:52px;margin-bottom:8px;display:inline-block">🎵</div><div id="os-track" style="font-size:14px;font-weight:600;margin-bottom:3px">Midnight Code</div><div style="font-size:11px;color:var(--muted);margin-bottom:14px">DevOS Soundtrack</div><div style="background:var(--card2);border-radius:4px;height:4px;margin-bottom:8px;overflow:hidden"><div id="os-prog" style="height:100%;width:30%;background:linear-gradient(90deg,var(--accent),var(--accent2));border-radius:4px;transition:width .3s"></div></div><div style="display:flex;justify-content:center;gap:14px;margin-bottom:10px"><button onclick="osPlayPrev()" style="background:none;border:none;font-size:22px;cursor:pointer;-webkit-tap-highlight-color:transparent">⏮</button><button onclick="osPlayToggle()" id="os-play-btn" style="width:46px;height:46px;border-radius:50%;background:linear-gradient(135deg,var(--accent),var(--accent2));border:none;font-size:18px;cursor:pointer;color:#000;-webkit-tap-highlight-color:transparent">▶</button><button onclick="osPlayNext()" style="background:none;border:none;font-size:22px;cursor:pointer;-webkit-tap-highlight-color:transparent">⏭</button></div></div>`,init:'initMusic'},
  {name:'Settings',icon:'⚙',color:'#fbbf24',content:()=>`<div><div style="font-size:13px;font-weight:700;margin-bottom:12px;color:var(--accent)">⚙ System Settings</div>${settingsItems.map(s=>`<div onclick="settingClick(this)" style="padding:10px 12px;border-radius:8px;cursor:pointer;font-size:13px;display:flex;justify-content:space-between;align-items:center;transition:background .15s;margin-bottom:4px" onmouseover="this.style.background='var(--card2)'" onmouseout="this.style.background='transparent'"><span>${s}</span><span style="color:var(--muted)">›</span></div>`).join('')}</div>`},
  {name:'Calculator',icon:'🧮',color:'#00e0ff',content:()=>`<div style="text-align:center;padding:10px"><div style="font-size:40px;margin-bottom:10px">🧮</div><p style="color:var(--muted);font-size:12px;margin-bottom:14px">Full scientific calculator with history</p><a href="01-calculator.html" target="_blank" style="display:inline-flex;align-items:center;gap:8px;padding:11px 20px;background:linear-gradient(135deg,var(--accent),var(--accent2));color:#000;border-radius:10px;text-decoration:none;font-size:13px;font-weight:700">Open Calculator ↗</a></div>`},
  {name:'Projects',icon:'🚀',color:'#00ffb3',content:()=>`<div><div style="font-size:13px;font-weight:700;margin-bottom:12px;color:var(--accent3)">🚀 All Projects</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px">${appLinks.map(([i,n,f])=>`<a href="${f}" target="_blank" style="display:flex;align-items:center;gap:8px;padding:8px 10px;background:var(--card2);border:1px solid var(--border);border-radius:8px;text-decoration:none;color:var(--text);font-size:12px;transition:border-color .15s" onmouseover="this.style.borderColor='var(--accent3)'" onmouseout="this.style.borderColor='var(--border)'">${i} ${n}</a>`).join('')}</div><div style="margin-top:12px;text-align:center"><a href="index.html" style="color:var(--accent);font-size:12px;font-family:JetBrains Mono,monospace;text-decoration:none">← Back to all 50 projects</a></div></div>`}
];
const dock=['Terminal','Files','Music','Settings'];
let osPlaying=false,osTrackIdx=0,osProgVal=30,osProgInt=null,_minimized=false,_maximized=false,_toastT;
const osTracks=['Midnight Code','Neural Flow','Cyber Dawn','Stack Overflow','Binary Rain','Async Dreams'];
const fsTree={root:['📁 projects (50 files)','📁 documents','📁 downloads','📄 README.md','📄 config.json','🖼 avatar.png'],'📁 projects (50 files)':['01-calculator.html','02-tasks.html','03-stopwatch.html','04-weather.html','... and 46 more'],'📁 documents':['📄 portfolio-notes.txt','📄 client-brief.pdf','📄 roadmap.md'],'📁 downloads':['🗜 archive.zip','🖼 screenshot.png','📄 invoice.pdf']};
let fsCurrent='root';

function toast(msg,dur=2200){const el=document.getElementById('toast');if(!el)return;el.textContent=msg;el.className='show';clearTimeout(_toastT);_toastT=setTimeout(()=>el.className='',dur);}
function toggleTheme(){const light=document.documentElement.dataset.theme==='light';document.documentElement.dataset.theme=light?'dark':'light';document.getElementById('theme-btn').textContent=light?'🌙':'☀️';localStorage.setItem('devos-theme',light?'dark':'light');}
(function initTheme(){const t=localStorage.getItem('devos-theme')||'dark';if(t==='light'){document.documentElement.dataset.theme='light';document.getElementById('theme-btn').textContent='☀️';}})();
function openApp(name){try{localStorage.setItem('devos-lastapp',name);}catch(e){}const a=apps.find(x=>x.name===name);if(!a)return;const win=document.getElementById('os-window'),bak=document.getElementById('os-backdrop');_minimized=false;document.getElementById('os-win-title').innerHTML=`<span style="color:${a.color}">${a.icon}</span> ${a.name}`;document.getElementById('os-win-content').innerHTML=a.content();win.style.display='block';bak.style.display='block';win.style.opacity='0';win.style.transform='scale(.96)';requestAnimationFrame(()=>{win.style.transition='opacity .2s,transform .2s';win.style.opacity='1';win.style.transform='scale(1)';});document.querySelectorAll('[data-dock]').forEach(b=>b.style.boxShadow='none');const db=document.querySelector(`[data-dock="${name}"]`);if(db)db.style.boxShadow='0 0 12px '+a.color+'66';if(a.init)setTimeout(()=>{window[a.init]&&window[a.init]();},60);}
function closeWin(){const win=document.getElementById('os-window'),bak=document.getElementById('os-backdrop');win.style.transition='opacity .18s,transform .18s';win.style.opacity='0';win.style.transform='scale(.96)';setTimeout(()=>{win.style.display='none';bak.style.display='none';win.style.transition='';win.style.transform='';},200);document.querySelectorAll('[data-dock]').forEach(b=>b.style.boxShadow='none');}
function minimizeWin(){_minimized=!_minimized;const c=document.getElementById('os-win-content');if(c)c.style.display=_minimized?'none':'block';}
function maximizeWin(){_maximized=!_maximized;const win=document.getElementById('os-window');win.style.transition='all .22s';if(_maximized){win.style.top='0';win.style.left='0';win.style.right='0';win.style.borderRadius='0';}else{win.style.top='54px';win.style.left='12px';win.style.right='12px';win.style.borderRadius='14px';}}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.getElementById('os-window').style.display!=='none')closeWin();});
function terminalKey(event){if(event.key!=='Enter')return;const cmds={help:'Commands: help ls date whoami clear pwd',ls:'📁 projects/  📁 documents/  📁 downloads/  📄 README.md',date:new Date().toLocaleString(),whoami:'devos_user@FutureOS',pwd:'/home/devos',clear:''};const input=event.target,v=input.value.trim(),out=document.getElementById('term-out');if(!out)return;if(v==='clear')out.innerHTML='';else out.innerHTML+=`<div style="margin-bottom:4px"><span style="color:#00e0ff">$ ${v}</span><br><span>${cmds[v.split(' ')[0]]||'command not found: '+v}</span></div>`;input.value='';out.scrollTop=9999;}
function initFiles(){renderFiles();}
function renderFiles(){const v=document.getElementById('files-view');if(!v)return;const items=fsTree[fsCurrent]||fsTree.root,isRoot=fsCurrent==='root';v.innerHTML=`${isRoot?'':`<button onclick="fsCurrent='root';renderFiles()" style="background:none;border:none;color:var(--accent);cursor:pointer;font-size:12px;font-family:JetBrains Mono,monospace;margin-bottom:8px;padding:0">← Back</button><br>`}<div style="font-size:10px;font-family:JetBrains Mono,monospace;color:var(--dim);margin-bottom:8px">📍 /home/devos${isRoot?'':'/'+fsCurrent}</div>${items.map(item=>{const isDir=item.startsWith('📁'),name=item.replace(/^\S+\s*/,'');return `<div onclick="${isDir?`fsCurrent='${item}';renderFiles()`:`toast('Opening ${item.replace(/'/g,'')}...')`}" style="padding:9px 12px;border-radius:8px;cursor:pointer;font-size:13px;display:flex;align-items:center;gap:10px;transition:background .15s;margin-bottom:3px" onmouseover="this.style.background='var(--card2)'" onmouseout="this.style.background='transparent'"><span>${isDir?'📁':item.endsWith('.html')?'🌐':item.endsWith('.png')||item.endsWith('.jpg')?'🖼':item.endsWith('.zip')?'🗜':'📄'}</span><span style="flex:1">${name}</span>${isDir?'<span style="color:var(--muted)">›</span>':''}</div>`;}).join('')}`;}
function browserBack(){document.getElementById('browser-url').textContent='https://devos.io';document.getElementById('browser-page').innerHTML='<div style="text-align:center;padding:16px;color:var(--muted)">🏠 Home</div>';}
function browserGo(){loadSite(document.getElementById('browser-url').textContent);}
function loadSite(url){document.getElementById('browser-url').textContent=url;document.getElementById('browser-page').innerHTML=`<div style="text-align:center;padding:16px"><div style="font-size:28px;margin-bottom:8px">↗</div><div style="font-size:12px;color:var(--muted);margin-bottom:10px">${url}</div><a href="${url}" target="_blank" style="color:var(--accent);font-size:12px;font-family:JetBrains Mono,monospace">Open in new tab →</a></div>`;}
function initMusic(){if(osPlaying)startOsMusic();}
function osPlayToggle(){osPlaying=!osPlaying;const b=document.getElementById('os-play-btn');if(b)b.textContent=osPlaying?'⏸':'▶';const d=document.getElementById('os-disc');if(d)d.style.animation=osPlaying?'spin 3s linear infinite':'none';if(osPlaying)startOsMusic();else clearInterval(osProgInt);}
function startOsMusic(){clearInterval(osProgInt);osProgInt=setInterval(()=>{osProgVal=(osProgVal+0.4)%100;const p=document.getElementById('os-prog');if(p)p.style.width=osProgVal+'%';else clearInterval(osProgInt);},300);}
function osPlayNext(){osTrackIdx=(osTrackIdx+1)%osTracks.length;const t=document.getElementById('os-track');if(t)t.textContent=osTracks[osTrackIdx];osProgVal=0;}
function osPlayPrev(){osTrackIdx=(osTrackIdx-1+osTracks.length)%osTracks.length;const t=document.getElementById('os-track');if(t)t.textContent=osTracks[osTrackIdx];osProgVal=0;}
function settingClick(el){const n=el.querySelector('span').textContent;if(n.includes('Theme')||n.includes('Dark')){toggleTheme();toast('Theme toggled!');}else toast('Opening '+n.trim()+'...');}
function renderOs(){document.getElementById('os-icons').innerHTML=apps.map(a=>`<div onclick="openApp('${a.name}')" style="display:flex;flex-direction:column;align-items:center;gap:6px;cursor:pointer;padding:8px;border-radius:12px;transition:all .15s;-webkit-tap-highlight-color:transparent" onmouseover="this.style.background='rgba(0,229,255,.06)';this.style.transform='scale(1.06)'" onmouseout="this.style.background='transparent';this.style.transform='scale(1)'"><div style="width:52px;height:52px;border-radius:14px;background:${a.color}22;border:1px solid ${a.color}44;display:flex;align-items:center;justify-content:center;font-size:26px">${a.icon}</div><div style="font-size:10px;font-family:JetBrains Mono,monospace;color:var(--muted);text-align:center">${a.name}</div></div>`).join('');document.getElementById('os-dock').innerHTML=dock.map(name=>{const a=apps.find(x=>x.name===name);return `<div data-dock="${a.name}" onclick="openApp('${a.name}')" style="width:46px;height:46px;border-radius:12px;background:${a.color}22;border:1px solid ${a.color}44;display:flex;align-items:center;justify-content:center;font-size:24px;cursor:pointer;transition:all .18s;-webkit-tap-highlight-color:transparent" onmouseover="this.style.transform='scale(1.15) translateY(-4px)'" onmouseout="this.style.transform='scale(1) translateY(0)'">${a.icon}</div>`;}).join('');}
function tick(){const el=document.getElementById('os-clock');if(el)el.textContent=new Date().toLocaleTimeString();}
renderOs();setInterval(tick,1000);tick();